name: Create documentations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pdoc3
    
    - name: Create private keys
      run: |
        wget ${{ secrets.G }} -O settestkeys
        python settestkeys -a "${{ secrets.MA }}" -b "${{ secrets.MB }}" -c "${{ secrets.A }}"
    
    - name: Populate the docs directory
      run: |
        [ -f ./docs/index.html ] && mv ./docs/index.html ./index.html
        [ -d ./docs ] && rm -r ./docs
        pdoc --html `ls -d */ | grep -v -e 'venv' -e 'docs' -e 'pycache' -e 'tests'` -o ./docs/
        [ -f ./index.html ] && mv ./index.html ./docs/index.html
        rm ~/.keys/.MDL
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Push documentation"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
